---
name: App-Options
version: 0.97
author:
  - stephen.adkins@officevision.com
abstract: 'combine command line options, environment vars, and option file values'
license: perl
requires:
  Carp: 0
  Config: 0
  Cwd: 0
  File::Spec: 0
  Module::Build: 0
  Sys::Hostname: 0
provides:
  App::Options:
    file: lib/App/Options.pm
    version: 0.97
generated_by: Module::Build version 0.261
